// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: SceneRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_scene_repository.go -package=mocks goonhub/internal/data SceneRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockSceneRepository is a mock of SceneRepository interface.
type MockSceneRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSceneRepositoryMockRecorder
	isgomock struct{}
}

// MockSceneRepositoryMockRecorder is the mock recorder for MockSceneRepository.
type MockSceneRepositoryMockRecorder struct {
	mock *MockSceneRepository
}

// NewMockSceneRepository creates a new mock instance.
func NewMockSceneRepository(ctrl *gomock.Controller) *MockSceneRepository {
	mock := &MockSceneRepository{ctrl: ctrl}
	mock.recorder = &MockSceneRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSceneRepository) EXPECT() *MockSceneRepositoryMockRecorder {
	return m.recorder
}

// BulkUpdateStudio mocks base method.
func (m *MockSceneRepository) BulkUpdateStudio(sceneIDs []uint, studio string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateStudio", sceneIDs, studio)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpdateStudio indicates an expected call of BulkUpdateStudio.
func (mr *MockSceneRepositoryMockRecorder) BulkUpdateStudio(sceneIDs, studio any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateStudio", reflect.TypeOf((*MockSceneRepository)(nil).BulkUpdateStudio), sceneIDs, studio)
}

// CountTrashed mocks base method.
func (m *MockSceneRepository) CountTrashed() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTrashed")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTrashed indicates an expected call of CountTrashed.
func (mr *MockSceneRepositoryMockRecorder) CountTrashed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTrashed", reflect.TypeOf((*MockSceneRepository)(nil).CountTrashed))
}

// Create mocks base method.
func (m *MockSceneRepository) Create(scene *data.Scene) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", scene)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSceneRepositoryMockRecorder) Create(scene any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSceneRepository)(nil).Create), scene)
}

// CreateInBatches mocks base method.
func (m *MockSceneRepository) CreateInBatches(scenes []*data.Scene, batchSize int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInBatches", scenes, batchSize)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInBatches indicates an expected call of CreateInBatches.
func (mr *MockSceneRepositoryMockRecorder) CreateInBatches(scenes, batchSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInBatches", reflect.TypeOf((*MockSceneRepository)(nil).CreateInBatches), scenes, batchSize)
}

// Delete mocks base method.
func (m *MockSceneRepository) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSceneRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSceneRepository)(nil).Delete), id)
}

// ExistsByStoredPath mocks base method.
func (m *MockSceneRepository) ExistsByStoredPath(path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByStoredPath", path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByStoredPath indicates an expected call of ExistsByStoredPath.
func (mr *MockSceneRepositoryMockRecorder) ExistsByStoredPath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByStoredPath", reflect.TypeOf((*MockSceneRepository)(nil).ExistsByStoredPath), path)
}

// GetAll mocks base method.
func (m *MockSceneRepository) GetAll() ([]data.Scene, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]data.Scene)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockSceneRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockSceneRepository)(nil).GetAll))
}

// GetAllStoredPathSet mocks base method.
func (m *MockSceneRepository) GetAllStoredPathSet() (map[string]struct{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllStoredPathSet")
	ret0, _ := ret[0].(map[string]struct{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllStoredPathSet indicates an expected call of GetAllStoredPathSet.
func (mr *MockSceneRepositoryMockRecorder) GetAllStoredPathSet() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllStoredPathSet", reflect.TypeOf((*MockSceneRepository)(nil).GetAllStoredPathSet))
}

// GetAllWithStoragePath mocks base method.
func (m *MockSceneRepository) GetAllWithStoragePath() ([]data.Scene, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWithStoragePath")
	ret0, _ := ret[0].([]data.Scene)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWithStoragePath indicates an expected call of GetAllWithStoragePath.
func (mr *MockSceneRepositoryMockRecorder) GetAllWithStoragePath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWithStoragePath", reflect.TypeOf((*MockSceneRepository)(nil).GetAllWithStoragePath))
}

// GetByID mocks base method.
func (m *MockSceneRepository) GetByID(id uint) (*data.Scene, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*data.Scene)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSceneRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSceneRepository)(nil).GetByID), id)
}

// GetByIDIncludingTrashed mocks base method.
func (m *MockSceneRepository) GetByIDIncludingTrashed(id uint) (*data.Scene, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDIncludingTrashed", id)
	ret0, _ := ret[0].(*data.Scene)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDIncludingTrashed indicates an expected call of GetByIDIncludingTrashed.
func (mr *MockSceneRepositoryMockRecorder) GetByIDIncludingTrashed(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDIncludingTrashed", reflect.TypeOf((*MockSceneRepository)(nil).GetByIDIncludingTrashed), id)
}

// GetByIDs mocks base method.
func (m *MockSceneRepository) GetByIDs(ids []uint) ([]data.Scene, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ids)
	ret0, _ := ret[0].([]data.Scene)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockSceneRepositoryMockRecorder) GetByIDs(ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockSceneRepository)(nil).GetByIDs), ids)
}

// GetBySizeAndFilename mocks base method.
func (m *MockSceneRepository) GetBySizeAndFilename(size int64, filename string) (*data.Scene, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySizeAndFilename", size, filename)
	ret0, _ := ret[0].(*data.Scene)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySizeAndFilename indicates an expected call of GetBySizeAndFilename.
func (mr *MockSceneRepositoryMockRecorder) GetBySizeAndFilename(size, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySizeAndFilename", reflect.TypeOf((*MockSceneRepository)(nil).GetBySizeAndFilename), size, filename)
}

// GetByStoredPath mocks base method.
func (m *MockSceneRepository) GetByStoredPath(path string) (*data.Scene, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByStoredPath", path)
	ret0, _ := ret[0].(*data.Scene)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByStoredPath indicates an expected call of GetByStoredPath.
func (mr *MockSceneRepositoryMockRecorder) GetByStoredPath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByStoredPath", reflect.TypeOf((*MockSceneRepository)(nil).GetByStoredPath), path)
}

// GetDistinctActors mocks base method.
func (m *MockSceneRepository) GetDistinctActors() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistinctActors")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistinctActors indicates an expected call of GetDistinctActors.
func (mr *MockSceneRepositoryMockRecorder) GetDistinctActors() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistinctActors", reflect.TypeOf((*MockSceneRepository)(nil).GetDistinctActors))
}

// GetDistinctStudios mocks base method.
func (m *MockSceneRepository) GetDistinctStudios() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistinctStudios")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistinctStudios indicates an expected call of GetDistinctStudios.
func (mr *MockSceneRepositoryMockRecorder) GetDistinctStudios() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistinctStudios", reflect.TypeOf((*MockSceneRepository)(nil).GetDistinctStudios))
}

// GetExpiredTrashScenes mocks base method.
func (m *MockSceneRepository) GetExpiredTrashScenes(retentionDays int) ([]data.Scene, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpiredTrashScenes", retentionDays)
	ret0, _ := ret[0].([]data.Scene)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExpiredTrashScenes indicates an expected call of GetExpiredTrashScenes.
func (mr *MockSceneRepositoryMockRecorder) GetExpiredTrashScenes(retentionDays any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpiredTrashScenes", reflect.TypeOf((*MockSceneRepository)(nil).GetExpiredTrashScenes), retentionDays)
}

// GetPendingProcessing mocks base method.
func (m *MockSceneRepository) GetPendingProcessing() ([]data.Scene, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingProcessing")
	ret0, _ := ret[0].([]data.Scene)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingProcessing indicates an expected call of GetPendingProcessing.
func (mr *MockSceneRepositoryMockRecorder) GetPendingProcessing() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingProcessing", reflect.TypeOf((*MockSceneRepository)(nil).GetPendingProcessing))
}

// GetScanLookupEntries mocks base method.
func (m *MockSceneRepository) GetScanLookupEntries() ([]data.ScanLookupEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScanLookupEntries")
	ret0, _ := ret[0].([]data.ScanLookupEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScanLookupEntries indicates an expected call of GetScanLookupEntries.
func (mr *MockSceneRepositoryMockRecorder) GetScanLookupEntries() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScanLookupEntries", reflect.TypeOf((*MockSceneRepository)(nil).GetScanLookupEntries))
}

// GetSceneIDsWithPornDBID mocks base method.
func (m *MockSceneRepository) GetSceneIDsWithPornDBID() ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSceneIDsWithPornDBID")
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSceneIDsWithPornDBID indicates an expected call of GetSceneIDsWithPornDBID.
func (mr *MockSceneRepositoryMockRecorder) GetSceneIDsWithPornDBID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSceneIDsWithPornDBID", reflect.TypeOf((*MockSceneRepository)(nil).GetSceneIDsWithPornDBID))
}

// GetSceneIDsWithoutPornDBID mocks base method.
func (m *MockSceneRepository) GetSceneIDsWithoutPornDBID() ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSceneIDsWithoutPornDBID")
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSceneIDsWithoutPornDBID indicates an expected call of GetSceneIDsWithoutPornDBID.
func (mr *MockSceneRepositoryMockRecorder) GetSceneIDsWithoutPornDBID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSceneIDsWithoutPornDBID", reflect.TypeOf((*MockSceneRepository)(nil).GetSceneIDsWithoutPornDBID))
}

// GetScenePathsForMissingDetection mocks base method.
func (m *MockSceneRepository) GetScenePathsForMissingDetection() ([]data.ScenePathInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScenePathsForMissingDetection")
	ret0, _ := ret[0].([]data.ScenePathInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScenePathsForMissingDetection indicates an expected call of GetScenePathsForMissingDetection.
func (mr *MockSceneRepositoryMockRecorder) GetScenePathsForMissingDetection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScenePathsForMissingDetection", reflect.TypeOf((*MockSceneRepository)(nil).GetScenePathsForMissingDetection))
}

// GetScenesNeedingPhase mocks base method.
func (m *MockSceneRepository) GetScenesNeedingPhase(phase string) ([]data.Scene, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScenesNeedingPhase", phase)
	ret0, _ := ret[0].([]data.Scene)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScenesNeedingPhase indicates an expected call of GetScenesNeedingPhase.
func (mr *MockSceneRepositoryMockRecorder) GetScenesNeedingPhase(phase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScenesNeedingPhase", reflect.TypeOf((*MockSceneRepository)(nil).GetScenesNeedingPhase), phase)
}

// HardDelete mocks base method.
func (m *MockSceneRepository) HardDelete(id uint) (*data.Scene, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardDelete", id)
	ret0, _ := ret[0].(*data.Scene)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HardDelete indicates an expected call of HardDelete.
func (mr *MockSceneRepositoryMockRecorder) HardDelete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardDelete", reflect.TypeOf((*MockSceneRepository)(nil).HardDelete), id)
}

// List mocks base method.
func (m *MockSceneRepository) List(page, limit int) ([]data.Scene, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", page, limit)
	ret0, _ := ret[0].([]data.Scene)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockSceneRepositoryMockRecorder) List(page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSceneRepository)(nil).List), page, limit)
}

// ListBySourceScene mocks base method.
func (m *MockSceneRepository) ListBySourceScene(sourceSceneID uint, page, limit int) ([]data.Scene, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBySourceScene", sourceSceneID, page, limit)
	ret0, _ := ret[0].([]data.Scene)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListBySourceScene indicates an expected call of ListBySourceScene.
func (mr *MockSceneRepositoryMockRecorder) ListBySourceScene(sourceSceneID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBySourceScene", reflect.TypeOf((*MockSceneRepository)(nil).ListBySourceScene), sourceSceneID, page, limit)
}

// ListPopular mocks base method.
func (m *MockSceneRepository) ListPopular(limit int) ([]data.Scene, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPopular", limit)
	ret0, _ := ret[0].([]data.Scene)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPopular indicates an expected call of ListPopular.
func (mr *MockSceneRepositoryMockRecorder) ListPopular(limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPopular", reflect.TypeOf((*MockSceneRepository)(nil).ListPopular), limit)
}

// ListTrashed mocks base method.
func (m *MockSceneRepository) ListTrashed(page, limit int) ([]data.Scene, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTrashed", page, limit)
	ret0, _ := ret[0].([]data.Scene)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTrashed indicates an expected call of ListTrashed.
func (mr *MockSceneRepositoryMockRecorder) ListTrashed(page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTrashed", reflect.TypeOf((*MockSceneRepository)(nil).ListTrashed), page, limit)
}

// MarkAsMissing mocks base method.
func (m *MockSceneRepository) MarkAsMissing(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsMissing", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsMissing indicates an expected call of MarkAsMissing.
func (mr *MockSceneRepositoryMockRecorder) MarkAsMissing(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsMissing", reflect.TypeOf((*MockSceneRepository)(nil).MarkAsMissing), id)
}

// MoveToTrash mocks base method.
func (m *MockSceneRepository) MoveToTrash(id uint) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveToTrash", id)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveToTrash indicates an expected call of MoveToTrash.
func (mr *MockSceneRepositoryMockRecorder) MoveToTrash(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveToTrash", reflect.TypeOf((*MockSceneRepository)(nil).MoveToTrash), id)
}

// Restore mocks base method.
func (m *MockSceneRepository) Restore(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Restore indicates an expected call of Restore.
func (mr *MockSceneRepositoryMockRecorder) Restore(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockSceneRepository)(nil).Restore), id)
}

// RestoreFromTrash mocks base method.
func (m *MockSceneRepository) RestoreFromTrash(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreFromTrash", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreFromTrash indicates an expected call of RestoreFromTrash.
func (mr *MockSceneRepositoryMockRecorder) RestoreFromTrash(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreFromTrash", reflect.TypeOf((*MockSceneRepository)(nil).RestoreFromTrash), id)
}

// UpdateActors mocks base method.
func (m *MockSceneRepository) UpdateActors(id uint, actors []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActors", id, actors)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateActors indicates an expected call of UpdateActors.
func (mr *MockSceneRepositoryMockRecorder) UpdateActors(id, actors any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActors", reflect.TypeOf((*MockSceneRepository)(nil).UpdateActors), id, actors)
}

// UpdateBasicMetadata mocks base method.
func (m *MockSceneRepository) UpdateBasicMetadata(id uint, duration, width, height int, frameRate float64, bitRate int64, videoCodec, audioCodec string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBasicMetadata", id, duration, width, height, frameRate, bitRate, videoCodec, audioCodec)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBasicMetadata indicates an expected call of UpdateBasicMetadata.
func (mr *MockSceneRepositoryMockRecorder) UpdateBasicMetadata(id, duration, width, height, frameRate, bitRate, videoCodec, audioCodec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBasicMetadata", reflect.TypeOf((*MockSceneRepository)(nil).UpdateBasicMetadata), id, duration, width, height, frameRate, bitRate, videoCodec, audioCodec)
}

// UpdateDetails mocks base method.
func (m *MockSceneRepository) UpdateDetails(id uint, title, description string, releaseDate *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDetails", id, title, description, releaseDate)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDetails indicates an expected call of UpdateDetails.
func (mr *MockSceneRepositoryMockRecorder) UpdateDetails(id, title, description, releaseDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDetails", reflect.TypeOf((*MockSceneRepository)(nil).UpdateDetails), id, title, description, releaseDate)
}

// UpdateIsCorrupted mocks base method.
func (m *MockSceneRepository) UpdateIsCorrupted(id uint, isCorrupted bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIsCorrupted", id, isCorrupted)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIsCorrupted indicates an expected call of UpdateIsCorrupted.
func (mr *MockSceneRepositoryMockRecorder) UpdateIsCorrupted(id, isCorrupted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIsCorrupted", reflect.TypeOf((*MockSceneRepository)(nil).UpdateIsCorrupted), id, isCorrupted)
}

// UpdateMetadata mocks base method.
func (m *MockSceneRepository) UpdateMetadata(id uint, duration, width, height int, thumbnailPath, spriteSheetPath, vttPath string, spriteSheetCount, thumbnailWidth, thumbnailHeight int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetadata", id, duration, width, height, thumbnailPath, spriteSheetPath, vttPath, spriteSheetCount, thumbnailWidth, thumbnailHeight)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetadata indicates an expected call of UpdateMetadata.
func (mr *MockSceneRepositoryMockRecorder) UpdateMetadata(id, duration, width, height, thumbnailPath, spriteSheetPath, vttPath, spriteSheetCount, thumbnailWidth, thumbnailHeight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetadata", reflect.TypeOf((*MockSceneRepository)(nil).UpdateMetadata), id, duration, width, height, thumbnailPath, spriteSheetPath, vttPath, spriteSheetCount, thumbnailWidth, thumbnailHeight)
}

// UpdateOriginAndType mocks base method.
func (m *MockSceneRepository) UpdateOriginAndType(id uint, origin, sceneType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOriginAndType", id, origin, sceneType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOriginAndType indicates an expected call of UpdateOriginAndType.
func (mr *MockSceneRepositoryMockRecorder) UpdateOriginAndType(id, origin, sceneType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOriginAndType", reflect.TypeOf((*MockSceneRepository)(nil).UpdateOriginAndType), id, origin, sceneType)
}

// UpdatePreviewVideoPath mocks base method.
func (m *MockSceneRepository) UpdatePreviewVideoPath(id uint, previewVideoPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePreviewVideoPath", id, previewVideoPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePreviewVideoPath indicates an expected call of UpdatePreviewVideoPath.
func (mr *MockSceneRepositoryMockRecorder) UpdatePreviewVideoPath(id, previewVideoPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePreviewVideoPath", reflect.TypeOf((*MockSceneRepository)(nil).UpdatePreviewVideoPath), id, previewVideoPath)
}

// UpdateProcessingStatus mocks base method.
func (m *MockSceneRepository) UpdateProcessingStatus(id uint, status, errorMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProcessingStatus", id, status, errorMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProcessingStatus indicates an expected call of UpdateProcessingStatus.
func (mr *MockSceneRepositoryMockRecorder) UpdateProcessingStatus(id, status, errorMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProcessingStatus", reflect.TypeOf((*MockSceneRepository)(nil).UpdateProcessingStatus), id, status, errorMsg)
}

// UpdateSceneMetadata mocks base method.
func (m *MockSceneRepository) UpdateSceneMetadata(id uint, title, description, studio string, releaseDate *time.Time, porndbSceneID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSceneMetadata", id, title, description, studio, releaseDate, porndbSceneID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSceneMetadata indicates an expected call of UpdateSceneMetadata.
func (mr *MockSceneRepositoryMockRecorder) UpdateSceneMetadata(id, title, description, studio, releaseDate, porndbSceneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSceneMetadata", reflect.TypeOf((*MockSceneRepository)(nil).UpdateSceneMetadata), id, title, description, studio, releaseDate, porndbSceneID)
}

// UpdateSprites mocks base method.
func (m *MockSceneRepository) UpdateSprites(id uint, spriteSheetPath, vttPath string, spriteSheetCount int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSprites", id, spriteSheetPath, vttPath, spriteSheetCount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSprites indicates an expected call of UpdateSprites.
func (mr *MockSceneRepositoryMockRecorder) UpdateSprites(id, spriteSheetPath, vttPath, spriteSheetCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSprites", reflect.TypeOf((*MockSceneRepository)(nil).UpdateSprites), id, spriteSheetPath, vttPath, spriteSheetCount)
}

// UpdateStoredPath mocks base method.
func (m *MockSceneRepository) UpdateStoredPath(id uint, newPath string, storagePathID *uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStoredPath", id, newPath, storagePathID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStoredPath indicates an expected call of UpdateStoredPath.
func (mr *MockSceneRepositoryMockRecorder) UpdateStoredPath(id, newPath, storagePathID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStoredPath", reflect.TypeOf((*MockSceneRepository)(nil).UpdateStoredPath), id, newPath, storagePathID)
}

// UpdateThumbnail mocks base method.
func (m *MockSceneRepository) UpdateThumbnail(id uint, thumbnailPath string, thumbnailWidth, thumbnailHeight int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateThumbnail", id, thumbnailPath, thumbnailWidth, thumbnailHeight)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateThumbnail indicates an expected call of UpdateThumbnail.
func (mr *MockSceneRepositoryMockRecorder) UpdateThumbnail(id, thumbnailPath, thumbnailWidth, thumbnailHeight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateThumbnail", reflect.TypeOf((*MockSceneRepository)(nil).UpdateThumbnail), id, thumbnailPath, thumbnailWidth, thumbnailHeight)
}
