// Code generated by MockGen. DO NOT EDIT.
// Source: goonhub/internal/data (interfaces: AppSettingsRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_app_settings_repository.go -package=mocks goonhub/internal/data AppSettingsRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	data "goonhub/internal/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAppSettingsRepository is a mock of AppSettingsRepository interface.
type MockAppSettingsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAppSettingsRepositoryMockRecorder
	isgomock struct{}
}

// MockAppSettingsRepositoryMockRecorder is the mock recorder for MockAppSettingsRepository.
type MockAppSettingsRepositoryMockRecorder struct {
	mock *MockAppSettingsRepository
}

// NewMockAppSettingsRepository creates a new mock instance.
func NewMockAppSettingsRepository(ctrl *gomock.Controller) *MockAppSettingsRepository {
	mock := &MockAppSettingsRepository{ctrl: ctrl}
	mock.recorder = &MockAppSettingsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppSettingsRepository) EXPECT() *MockAppSettingsRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAppSettingsRepository) Get() (*data.AppSettingsRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(*data.AppSettingsRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAppSettingsRepositoryMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAppSettingsRepository)(nil).Get))
}

// UpdateShortsSettings mocks base method.
func (m *MockAppSettingsRepository) UpdateShortsSettings(maxDuration int, saveDir *string, searchDefault string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateShortsSettings", maxDuration, saveDir, searchDefault)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateShortsSettings indicates an expected call of UpdateShortsSettings.
func (mr *MockAppSettingsRepositoryMockRecorder) UpdateShortsSettings(maxDuration, saveDir, searchDefault any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateShortsSettings", reflect.TypeOf((*MockAppSettingsRepository)(nil).UpdateShortsSettings), maxDuration, saveDir, searchDefault)
}

// Upsert mocks base method.
func (m *MockAppSettingsRepository) Upsert(record *data.AppSettingsRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockAppSettingsRepositoryMockRecorder) Upsert(record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockAppSettingsRepository)(nil).Upsert), record)
}
